[package]
name    = "mytool"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
publish = false
description = "CLI multiusos: hashes de archivos y generación de contraseñas"

[[bin]]
name = "mytool"
path = "src/main.rs"

[dependencies]
clap          = { version = "4", features = ["derive", "env", "wrap_help"] }
owo-colors    = "4"
indicatif     = "0.17"
blake3        = "1"
sha2          = "0.10"
hex           = "0.4"
rand          = "0.9"
anyhow        = "1"
rayon         = "1"
serde         = { version = "1", features = ["derive"] }
serde_json    = "1"
tracing            = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile   = "3"
